### ISSUE TITLE
Pixel not detected as antialiased (?)

### ISSUE THREAD

**Issue by tonyhignett** [gemini-testing/looks-same#108]
I've got two images which only differ in some antialiasing. When I diff them, one pixel shows up as different, even though it doesn't seem to undergo any more of a change than a few others near it. Perhaps it's not being detected as antialiased when it should be?

Here are the images and the diff:
![a](https://github.com/user-attachments/assets/63066c01-9054-4db2-a5d8-6c635f68e9e5)
![b](https://github.com/user-attachments/assets/28cc77ca-e126-4a3f-b8f7-17bc2ea2a628)
![diff](https://github.com/user-attachments/assets/6658e92d-4002-4404-92d5-c9370c2853be)

They come from two runs of our visual snapshot tests, which ran on exactly the same environment (using docker). I've cropped them down from the real images.

**Comment by DudaGod** [comment]
Hello. 

Сan you upload these files somewhere else so that I can download and check them using looks-same? Uploaded images to this issue cannot be downloaded (these links point to private-user-images.githubusercontent.com).

**Comment by tonyhignett** [comment]
Sorry, here they are:

a.png: https://drive.google.com/file/d/1Zu2jw7xEmVG31GUv5jPrQfQfjjXgys-A/view
b.png: https://drive.google.com/file/d/1j6GfQ8wokhTBGYnJk7-pFyEc290bFMAU/view
diff.png: https://drive.google.com/file/d/1muSMOaoVgGKW2KBc7kR166YiMZHUYXv-/view

**Comment by DudaGod** [comment]
In order to detect antialising we use algorithm which is described detailed here - http://www.eejournal.ktu.lt/index.php/elt/article/view/10058/5000. I look on our implementation and didn't find a bug.

In your images there is a diff in one pixel, on `a.png` it is `#798189` and on `b.png` it is `#727b84`. They are considered the same only when using the value `tolerance: 2.44`. 

So here you have two options:
- increase tolerance to `2.44`
- look at result of comparsion which returns `differentPixels` count. And you can say that images are equal if for example only 1 pixel is different. But it depends on your task, maybe you must strictly validate each pixel.

**Comment by tonyhignett** [comment]
Thanks, we'll see how increasing the tolerance works out.
