### ISSUE TITLE
what's the difference between looks-same and pixelmatch?

### ISSUE THREAD

**Issue by FishBlanche** [gemini-testing/looks-same#88]
what's the difference between looks-same and pixelmatch?

**Comment by KuznetsovRoman** [comment]
## Color comparison
- `looks-same` is using [CIEDE2000](https://en.wikipedia.org/wiki/Color_difference#CIEDE2000) color difference
- `pixelmatch` is using YIQ NTSC transmission color space

**CIEDE2000** is much closer to human color perception, so with `pixelmatch` you would have weird comparison results (described in https://github.com/mapbox/pixelmatch/issues/127)

## Antialiasing
- `looks-same` has configurable `antialiasingTolerance`
- `pixelmatch` has some antialiasing tolerance, but its not configurable, therefore could not be adjusted to your needs

## Ignore caret
- `looks-same` has `ignoreCaret` option
- `pixelmatch`: "this is the type of thing that should be handled outside of pixelmatch" (https://github.com/mapbox/pixelmatch/issues/59#issuecomment-499555398)

## Boilerplate
- `looks-same` has no boilerplate: you can pass imageBuffer or imagePath to a function and that's it
- `pixelmatch` forces you to write some bulky code (assuming you are using it in `Node.js`): https://www.npmjs.com/package/pixelmatch#user-content-nodejs

## Environment
- `looks-same` is **Node.js only** solution (because it uses `libvips` under the hood)
- `pixelmatch` can be used in browsers

## Conclusion
If you need to run your code in some browser, you should use `pixelmatch`.
If you need configurable `antialiasingTolerance` and `ignoreCaret` options (it is usefull to compare screenshots), or if you want to compare images considering human color perception, you should use `looks-same`
